In [18]:
import pandas as pd
import os
import numpy as np

In [19]:
def load_train_data(datatype='int32', MAX_NUMBER_NODES=9, NUMBER_NODES='7_9'):
  features_length = (MAX_NUMBER_NODES * MAX_NUMBER_NODES - MAX_NUMBER_NODES) // 2

  train_df = pd.read_csv(os.path.join('..', 'datasets', f'dataset_{NUMBER_NODES}_train.csv'))
  val_df = pd.read_csv(os.path.join('..', 'datasets', f'dataset_{NUMBER_NODES}_val.csv'))

  train_df = pd.concat((train_df, val_df))

  def get_tuple_tensor_dataset(row):
      X = row[0 : features_length].astype(datatype)
      Y = row[features_length + 1: ].astype(datatype) # Pula a banda otima na posicao 0
      return X, Y
  train_dataset = list(map(get_tuple_tensor_dataset, train_df.to_numpy()))

  X = []
  Y = []
  for x, y in train_dataset:
      X.append(x)
      Y.append(y)
  x_train = np.array(X)
  y_train = np.array(Y)

  return x_train, y_train

In [20]:
x_train, y_train = load_train_data()

In [25]:
for x, y in zip(x_train, y_train):
  if -1 not in x:
    print("first not masked features and labels:")
    print(x)
    print(f'x shape - {x.shape}')
    print(y)
    print(f'y shape - {y.shape}')
    print("")
    break

for x, y in zip(x_train, y_train):
  if -1 in x:
    print("first masked features and labels:")
    print(x)
    print(f'x shape - {x.shape}')
    print(y)
    print(f'y shape - {y.shape}')
    break

first not masked features and labels:
[0 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1]
x shape - (36,)
[5 0 4 1 8 7 6 2 3]
y shape - (9,)

first masked features and labels:
[ 0  0  0  1  1  1  0  0  0  1  1  0  0  0  1  0  0  1  0  0  0 -1 -1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
x shape - (36,)
[ 4  5  0  1  6  3  2 -1 -1]
y shape - (9,)
