In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import random
import cv2
from PIL import Image

In [15]:
# NUMBER_NODES = 9
NUMBER_NODES = 7
# NUMBER_NODES = 5
DATASET_PATH = f'../../../../datasets/examples/opt_band_{NUMBER_NODES}_nodes_graph.csv'

def getGraph(upperTriangleAdjMatrix):
    dense_adj = np.zeros((NUMBER_NODES, NUMBER_NODES))
    dense_adj = np.zeros((NUMBER_NODES, NUMBER_NODES))
    k = 0
    for i in range(NUMBER_NODES):
        for j in range(NUMBER_NODES):
            if i == j:
                continue
            elif i < j:
                dense_adj[i][j] = upperTriangleAdjMatrix[k]
                k += 1
            else:
                dense_adj[i][j] = dense_adj[j][i]
    return dense_adj  


def saveAdjImg(graphInput, filename, path):
    graph_adj = getGraph(graphInput)
    
    plt.imshow(graph_adj, cmap="gray")
    plt.xticks([])
    plt.yticks([])
    plt.savefig(f'{path}/{filename}')
    plt.clf()
    img = cv2.imread(f'{path}/{filename}')
    img = cv2.resize(img, (32, 32))
    cv2.imwrite(f'{path}/{filename}', img)

def saveImg(graphInput, filename, path):
    adj = getGraph(graphInput)

    w, h = NUMBER_NODES, NUMBER_NODES
    data = np.zeros((h, w, 3), dtype=np.uint8)

    # print(w)
    # print(h)
    # print(adj)
    # print(data.shape)

    for i in range(len(adj)):
        for j in range(len(adj)):
            if adj[i, j] == 1:
                data[i, j] = np.array([255, 255, 255])
    img = Image.fromarray(data, 'RGB')
    resized = img.resize((32, 32), Image.NEAREST)
    # print(resized.size)
    resized.save(f'{path}/{filename}')

In [ ]:
featuresNumber = ((NUMBER_NODES * NUMBER_NODES - NUMBER_NODES) // 2 )
df = pd.read_csv(DATASET_PATH)
train_val_df = df.sample(frac=0.9)
df_remaining = df.drop(index=train_val_df.index)

annotations_file = {
    'file_name': [],
    'label': []
}

i = 0
for input in train_val_df.values:
    features = input[ : featuresNumber]
    path = f'./dataset_{NUMBER_NODES}'
    if not os.path.exists(path):
        os.makedirs(path)
    filename = f'adj_{i}.jpg'
    labels = input[ featuresNumber + 1: ]
    annotations_file['file_name'].append(filename)
    annotations_file['label'].append(random.choice([0,1,2]))
    saveImg(features, filename, path)
    i += 1

df = pd.DataFrame(annotations_file)
df.to_csv("annotations_file_train.csv", index=False)

In [17]:
annotations_file_val = {
    'file_name': [],
    'label': []
}

for input in df_remaining.values:
    features = input[ : featuresNumber]
    path = f'./dataset_val_{NUMBER_NODES}'
    if not os.path.exists(path):
        os.makedirs(path)
    filename = f'adj_{i}.jpg'
    labels = input[ featuresNumber + 1: ]
    annotations_file_val['file_name'].append(filename)
    annotations_file_val['label'].append(random.choice([0,1,2]))
    saveImg(features, filename, path)
    i += 1
  
df = pd.DataFrame(annotations_file)
df.to_csv("annotations_file_val.csv", index=False)

7
7
[[0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
(7, 7, 3)
(32, 32)
7
7
[[0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]]
(7, 7, 3)
(32, 32)
7
7
[[0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0.]]
(7, 7, 3)
(32, 32)
7
7
[[0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 1. 1. 1. 0.]]
(7, 7, 3)
(32, 32)
7
7
[[0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]]
(7, 7, 3)
(32, 32)
7
7
[[0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0

In [18]:
# img = cv2.imread('Graph_CustomLoss.png')
# img = cv2.resize(img, (64, 64))
# cv2.imwrite(f'dale.jpg', img)

In [19]:
# from PIL import Image
# import networkx as nx
# import numpy as np

# G = nx.Graph()
# G.add_edges_from([(1, 2), (1, 3)])
# adj = nx.to_numpy_matrix(G)

# w, h = 3, 3
# data = np.zeros((h, w, 3), dtype=np.uint8)
# for i in range(len(adj)):
#     for j in range(len(adj)):
#         if adj[i, j] == 1:
#             # data[i:170, j:170] = np.array([255, 255, 255])
#             data[i, j] = np.array([255, 255, 255])
# # data[0:256, 0:256] = [255, 255, 255] # red patch in upper left
# img = Image.fromarray(data, 'RGB')
# fixed_height = 1024
# # height_percent = (fixed_height / float(img.size[1]))
# # width_size = int((float(img.size[0]) * float(height_percent)))
# resized = img.resize((32, 32), Image.NEAREST)
# print(resized.size)
# resized.save('my.png')
# # resized.show()