In [1]:
import numpy as np
import sys

sys.path.append('..')
from classes.NetworkXGraph import Graph

In [2]:
# Building graph

    # file_format: Adjacency TSV (Tab-Separated Values)
        # (Row, Col, Value) tuple describing the adjacency matrix of the graph in tab separated format.
        # Adjacency matrix is of size Num_vertices x Num_vertices
    # file: cora.cites
    # num of nodes:      2708
    # num of edges:      5278
    # num of triangles:  1630

g = Graph()
g.build_from_tsv('../datasets/cora.cites')

elapsed time in seconds: 0.210339


In [3]:
# calculating degree of nodes

degree = g.get_degree()
max_degree = max(degree, key=degree.get)
print('Degree calculated to %d nodes, max degree: %d' % (len(degree), max_degree))

Degree calculated to 2708 nodes, max degree: 35


In [4]:
# Transform in subgraph list if disconnected
if not g._is_connected:
    g.transform_subgraph_list(delete_original= True)

Original graph deleted.
78 subgraphs created.


In [5]:
# calculating eccentricity of nodes
ecc = g.get_eccentricity()
print(len(ecc))
#ecc

2708


In [6]:
# calculating position of nodes

pos = g.get_position()
print(len(pos))
#pos

211


In [72]:
# transform dicts in numpy array

feat = np.zeros((2708,4), dtype='int')
count = 0
for key in degree.keys():
    feat[count,0] = key
    feat[count,1] = degree[key]
    feat[count,2] = ecc[key]
    feat[count,3] = pos[key] if key in pos else 0
    count = count + 1

# validating
print(degree[4330], ecc[4330], pos[4330])
print(degree[312409], ecc[312409], pos[312409])
print(degree[1154074], ecc[1154074], pos[1154074])
    
print(np.select(feat[:,0] == 4330, feat))
print(np.select(feat[:,0] == 312409, feat))
print(np.select(feat[:,0] == 1154074, feat))

40 10 1
1 19 2
1 19 2
[4330   40   10    1]
[312409      1     19      2]
[1154074       1      19       2]


In [30]:
# generating file with features
