In [69]:
%matplotlib inline


What is PyTorch?
================

It’s a Python based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [70]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [71]:
# Returns a tensor filled with uninitialized data.
x = torch.empty(5, 3)
print(x)

tensor([[-2.3566e-29,  4.5668e-41,  1.0489e+26],
        [ 3.0625e-41,  0.0000e+00,  0.0000e+00],
        [ 7.0065e-45,         nan,  3.9947e+25],
        [ 3.0625e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  7.0065e-45]])


Construct a randomly initialized matrix:



In [72]:
# Returns a tensor filled with random numbers from a uniform distribution on the interval :math:`[0, 1)`
x = torch.rand(5, 3)
print(x)

tensor([[0.8852, 0.2298, 0.2068],
        [0.6522, 0.2104, 0.9477],
        [0.0284, 0.6354, 0.9465],
        [0.3345, 0.5368, 0.1409],
        [0.5269, 0.7535, 0.6126]])


Construct a matrix filled zeros and of dtype long:



In [73]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [74]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [75]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

# torch.randn_like(input)
# Returns a tensor with the same size as :attr:`input` that is filled with
# random numbers from a normal distribution with mean 0 and variance 1.
# ``torch.randn_like(input)`` is equivalent to
# ``torch.randn(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)``.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.7274,  0.0534,  0.5162],
        [ 0.1615, -0.8993,  0.1520],
        [ 0.4798, -0.6454,  0.4514],
        [-0.1590,  0.4333, -0.6481],
        [-1.2572, -0.5780, -1.2345]])


Get its size:



In [76]:
print(x.size()) # same of x.shape() in numpy

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [77]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-1.5103,  0.5468,  1.1277],
        [ 0.3878, -0.1426,  0.1884],
        [ 1.4749, -0.3050,  1.0438],
        [ 0.5556,  0.4548, -0.2119],
        [-0.6054, -0.2543, -1.0511]])


Addition: syntax 2



In [78]:
print(torch.add(x, y))

tensor([[-1.5103,  0.5468,  1.1277],
        [ 0.3878, -0.1426,  0.1884],
        [ 1.4749, -0.3050,  1.0438],
        [ 0.5556,  0.4548, -0.2119],
        [-0.6054, -0.2543, -1.0511]])


Addition: providing an output tensor as argument



In [79]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.5103,  0.5468,  1.1277],
        [ 0.3878, -0.1426,  0.1884],
        [ 1.4749, -0.3050,  1.0438],
        [ 0.5556,  0.4548, -0.2119],
        [-0.6054, -0.2543, -1.0511]])


Addition: in-place



In [80]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.5103,  0.5468,  1.1277],
        [ 0.3878, -0.1426,  0.1884],
        [ 1.4749, -0.3050,  1.0438],
        [ 0.5556,  0.4548, -0.2119],
        [-0.6054, -0.2543, -1.0511]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [81]:
print(x)
print(x[:, 1])

tensor([[-1.7274,  0.0534,  0.5162],
        [ 0.1615, -0.8993,  0.1520],
        [ 0.4798, -0.6454,  0.4514],
        [-0.1590,  0.4333, -0.6481],
        [-1.2572, -0.5780, -1.2345]])
tensor([ 0.0534, -0.8993, -0.6454,  0.4333, -0.5780])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [82]:
x = torch.randn(4, 4)
print('x before', x)
print('y before', y)
y = x.view(16) # y receive data from x with new resize 16
print('y after', y)
print('z before', z)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
                   # Once x has 4x4 dimensions and z must have ? x 8 then -1 infers 2 because 2 x 8 = 16
print('z after', z)
print(x.size(), y.size(), z.size())

x before tensor([[ 1.0295, -0.2119, -0.2968,  1.7359],
        [-0.6117,  1.5781, -1.0097,  1.4736],
        [ 0.3315,  0.6105,  1.3674, -1.9057],
        [-1.0063, -0.6806,  0.3284, -0.0165]])
y before tensor([[-1.5103,  0.5468,  1.1277],
        [ 0.3878, -0.1426,  0.1884],
        [ 1.4749, -0.3050,  1.0438],
        [ 0.5556,  0.4548, -0.2119],
        [-0.6054, -0.2543, -1.0511]])
y after tensor([ 1.0295, -0.2119, -0.2968,  1.7359, -0.6117,  1.5781, -1.0097,  1.4736,
         0.3315,  0.6105,  1.3674, -1.9057, -1.0063, -0.6806,  0.3284, -0.0165])
z before tensor([[ 0.2177,  0.2238,  0.8668, -1.6404, -2.2833, -1.7338,  0.8458, -0.7985],
        [-0.3274,  0.8263,  0.4034,  0.4373,  0.9517,  0.0885, -0.7764, -0.1757]])
z after tensor([[ 1.0295, -0.2119, -0.2968,  1.7359, -0.6117,  1.5781, -1.0097,  1.4736],
        [ 0.3315,  0.6105,  1.3674, -1.9057, -1.0063, -0.6806,  0.3284, -0.0165]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [83]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0987])
0.09871464967727661


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [93]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [94]:
b = a.numpy() # CAUTION: b is a referenced value. Changes in a will be reflected in b
              # To prevent that, use copy() (e.g.: b = a.numpy().copy())
print(b)
print(type(a), type(b))

[1. 1. 1. 1. 1.]
<class 'torch.Tensor'> <class 'numpy.ndarray'>


See how the numpy array changed in value.



In [95]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [97]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a) # CAUTION: b is a referenced value. Changes in a will be reflected in b
                        # To prevent that, use copy()
print(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [99]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print('torch.cuda is not available')

torch.cuda is not available
