In [5]:
import numpy as np
import random

rand_indices = np.random.permutation(10) # len(rand_indices) = 2708
print(rand_indices)

test = rand_indices[:5]
print(test)
train = list(rand_indices[5:])
print(train)

print(train[:3])
random.shuffle(train)
print(train)
print(train[:3])


[6 8 4 2 5 7 0 1 9 3]
[6 8 4 2 5]
[7, 0, 1, 9, 3]
[7, 0, 1]
[7, 1, 0, 9, 3]
[7, 1, 0]
[ 0 10 20 30 40 50]


In [2]:
graph_data = np.loadtxt('cora/cora_graph.feat', np.int64)
graph_data

#print(np.min(graph_data, axis=0))
#print(np.max(graph_data, axis=0))

array([[    35,    168,     12,      0],
       [  1033,      5,     13,      0],
       [103482,      6,     13,      0],
       ...,
       [853155,      4,     14,      0],
       [853115,      4,     13,      0],
       [853118,      2,     13,      0]])

In [1]:
from sklearn import preprocessing
import numpy as np
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

scaler = preprocessing.StandardScaler().fit(X_train)


array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [5]:
print(X_train)
X_norm = scaler.transform(X_train)
X_norm

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [4]:


#x= np.random.random((3,3))
x = np.array([[0.89372503, 0.99865458, 0.77120044],
              [0.67632984, 0.99990084, 0.64110391],
              [0.34845794, 0.66557903, 0.29031742]])
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


from sklearn import preprocessing
#min_max_scaler = preprocessing.MinMaxScaler()
min_max_scaler = preprocessing.StandardScaler(with_mean=False)
X_train_minmax = min_max_scaler.fit_transform(x)
print(X_train_minmax)

teste = np.array([[168, 1, 2]]) 
teste_scale = min_max_scaler.transform(teste)
teste_scale


Original Array:
[[0.89372503 0.99865458 0.77120044]
 [0.67632984 0.99990084 0.64110391]
 [0.34845794 0.66557903 0.29031742]]
After normalization:
[[0.85036881 0.99824367 0.67769766]
 [0.54399865 1.         0.49435553]
 [0.08193613 0.52884777 0.        ]]
[[2.6923152  4.50287118 2.36778485]
 [1.72233013 4.5107936  1.72721203]
 [0.25941437 2.38552314 0.        ]]


/opt/conda/lib/python2.7/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[531.89739239,   4.5107936 ,   6.98773215]])